models:
  - name: GPT-4
    provider: openai
  - name: Claude
    provider: anthropic
  - name: Mistral
    provider: huggingface
  - name: TinyLlama
    provider: huggingface
  - name: Phi-2
    provider: huggingface
  - name: Falcon
    provider: huggingface
  - name: LLaMA-3
    provider: huggingface
  - name: Command R+
    provider: cohere
  - name: Yi-34B
    provider: huggingface
  - name: GPT-3.5
    provider: openai
